# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  encoding: utf8
  database: appdev_facetest
  pool: 5
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  encoding: utf8
  database: appdev_facetest_test
  pool: 5
  username: root
  password:
  host: localhost
  
